# Please don't use ADO UI defined scheduled triggers because it takes precedence over YAML scheduled triggers.
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/scheduled-triggers
schedules:
- cron: "0 0 * * *"
  displayName: Daily Midnight Build
  branches:
    include:
    - master

pr: none

pool:
  vmImage: 'windows-2019'

steps:

- task: DotNetCoreCLI@2
  displayName: Build for Version Bump
  inputs:
    command: 'custom'
    custom: 'msbuild'
    arguments: 'build.proj'

- task: ComponentGovernanceComponentDetection@0
  displayName: Component Detection
  inputs:
    scanType: 'Register'
    verbosity: 'Normal'
    alertWarningLevel: 'High'

- task: PowerShell@2
  displayName: 'Install platyPS'
  inputs:
    targetType: 'inline'
    script: 'Install-Module platyPS -Force -Confirm:$false -Scope CurrentUser'
    pwsh: true

#v2.1.3 has a Publish-Module bug
- task: PowerShell@2
  displayName: 'Install PowerShellGet'
  inputs:
    targetType: 'inline'
    script: 'Install-Module PowerShellGet -Force -Confirm:$false -Scope CurrentUser -SkipPublisherCheck'
    pwsh: true

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '.\RunVersionController.ps1 -Release "August 2020"'
    errorActionPreference: 'continue'
    pwsh: true
    workingDirectory: './tools'

- task: DotNetCoreCLI@2
  displayName: Buidl for Release
  inputs:
    command: 'custom'
    custom: 'msbuild'
    arguments: 'build.proj /t:Build;GenerateHelp /p:Configuration=Release'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: 'custom'
    custom: 'msbuild'
    arguments: 'build.proj /t:Publish /p:Configuration=Release;NuGetKey=123456'

